CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role varchar(30) NOT NULL,
    status varchar(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    status varchar(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT orders_customer FOREIGN KEY (customer_id) REFERENCES users(id),
    CONSTRAINT orders_part FOREIGN KEY (part_id) REFERENCES parts(id)
);

CREATE TABLE IF NOT EXISTS operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    status varchar(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    maintenance_requested BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS part_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    name varchar(255) NOT NULL,
    description TEXT NOT NULL,
    status varchar(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT part_requests_customer FOREIGN KEY (customer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS order_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    operation_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),
    time_per_part INTEGER NOT NULL CHECK (time_per_part > 0),
    status varchar(30) NOT NULL,
    ready_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    planned_end_at TIMESTAMPTZ,

    CONSTRAINT order_operations_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT order_operations_operation FOREIGN KEY (operation_id) REFERENCES operations(id),
    CONSTRAINT unique_order_sequence UNIQUE (order_id, sequence)
);

CREATE TABLE IF NOT EXISTS part_operations (
    part_id BIGINT NOT NULL,
    operation_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL CHECK (sequence > 0),

    CONSTRAINT pk_part_operations PRIMARY KEY (part_id, sequence),
    CONSTRAINT part_operations_part FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT part_operations_operation FOREIGN KEY (operation_id) REFERENCES operations(id)
);

CREATE TABLE IF NOT EXISTS machine_operations (
    machine_id BIGINT NOT NULL,
    operation_id BIGINT NOT NULL,

    CONSTRAINT pk_machine_operations PRIMARY KEY (machine_id, operation_id),
    CONSTRAINT machine_operations_machine FOREIGN KEY (machine_id) REFERENCES machines(id),
    CONSTRAINT machine_operations_operation FOREIGN KEY (operation_id) REFERENCES operations(id),
    CONSTRAINT unique_machine_operation UNIQUE (machine_id)
);

CREATE TABLE IF NOT EXISTS order_operation_machines (
    order_operation_id BIGINT NOT NULL,
    machine_id BIGINT NOT NULL,

    CONSTRAINT pk_order_operation_machines PRIMARY KEY (order_operation_id, machine_id),
    CONSTRAINT order_operation_machines_order_operation FOREIGN KEY (order_operation_id) REFERENCES order_operations(id),
    CONSTRAINT order_operation_machines_machine FOREIGN KEY (machine_id) REFERENCES machines(id)
);